preset_base: ${PRESET_BASE}
chain_id: ${CHAIN_ID}
deposit_contract_address: "${DEPOSIT_CONTRACT_ADDRESS}"
mnemonic: ${EL_AND_CL_MNEMONIC}
el_premine: {}
el_premine_addrs: ${EL_PREMINE_ADDRS}
additional_preloaded_contracts: ${ADDITIONAL_PRELOADED_CONTRACTS}
genesis_timestamp: ${GENESIS_TIMESTAMP}
genesis_delay: ${GENESIS_DELAY}
genesis_gaslimit: ${GENESIS_GASLIMIT}
slot_duration_in_seconds: ${SLOT_DURATION_IN_SECONDS}
terminal_total_difficulty: ${TERMINAL_TOTAL_DIFFICULTY}
altair_fork_epoch: ${ALTAIR_FORK_EPOCH}
bellatrix_fork_epoch: ${BELLATRIX_FORK_EPOCH}
capella_fork_epoch: ${CAPELLA_FORK_EPOCH}
deneb_fork_epoch: ${DENEB_FORK_EPOCH}
electra_fork_epoch: ${ELECTRA_FORK_EPOCH}
fulu_fork_epoch: ${FULU_FORK_EPOCH}
target_blobs_per_block_cancun: 3
max_blobs_per_block_cancun: 6
basefee_update_fraction_cancun: 3338477
target_blobs_per_block_prague: ${TARGET_BLOBS_PER_BLOCK_ELECTRA}
max_blobs_per_block_prague: ${MAX_BLOBS_PER_BLOCK_ELECTRA}
basefee_update_fraction_prague: ${BASEFEE_UPDATE_FRACTION_ELECTRA}
target_blobs_per_block_osaka: ${TARGET_BLOBS_PER_BLOCK_FULU}
max_blobs_per_block_osaka: ${MAX_BLOBS_PER_BLOCK_FULU}
basefee_update_fraction_osaka: ${BASEFEE_UPDATE_FRACTION_FULU}
